
package:
    name: stracking
    version: v0.1.3

source:
  git_url: https://github.com/sylvainprigent/stracking.git


requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy
        - cython

    run:
        - python

test:
    imports:
        - setuptools


about:
    home: https://github.com/sylvainprigent/stracking
