
package:
    name: stracking
    version: v0.1.5

source:
  git_url: https://github.com/sylvainprigent/stracking.git


requirements:
    build:
        - python=3.9
        - setuptools
        - numpy=1.24.4
        - scipy=1.9.3
        - scikit-image=0.19.3
        - pandas==1.5.3

    run:
        - python

test:
    imports:
        - setuptools


about:
    home: https://github.com/sylvainprigent/stracking
