
package:
    name: stracking
    version: v0.1.4

source:
  git_url: https://github.com/sylvainprigent/stracking.git


requirements:
    build:
        - python=3.8
        - setuptools
        - numpy=1.16.6
        - scipy=1.7.1
        - scikit-image=0.18.3

    run:
        - python

test:
    imports:
        - setuptools


about:
    home: https://github.com/sylvainprigent/stracking
