package:
    name: atlas
    version: "1.0.2"
  
source:
  git_url: https://gitlab.inria.fr/serpico/atlas.git
  git_rev: v1.0.2
  
build:
  number: 1
  
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - libpng
    - libtiff
    - gsl
    - llvm-openmp # [osx]
    - llvm-openmp # [win]
  host:
    - gsl
    - libpng
    - libtiff
  run:
    - gsl
    - libpng
    - libtiff
  
test:
  commands:
    - "! test -d $PREFIX/bin/atlas"                # [unix]
    - if not exist %PREFIX%\\bin\\atlas.exe exit 1     # [win]
  
about:
  home: 'https://gitlab.inria.fr/serpico/atlas'
  summary: 'Spot detection in 2D images'
  license: GPL3
