package:
    name: juglab-noise2void
    version: "0.3.1"
  
source:
  git_url: https://github.com/juglab/n2v.git
  git_rev: v0.3.1
  
requirements:
  build:
    - python

  run :
    - python
  
test:
  imports :
    - os                # [python]
  
about:
  home: 'https://github.com/juglab/n2v'
  summary: 'Noise2Void - Learning Denoising from Single Noisy Images'
  